In [18]:
import numpy as np
import pandas as pd

In [19]:
data={
    'Name': ['Ali', 'Sara', 'Omar', 'Ayesha', 'Bilal', 'Fatima', 'Hassan', 'Nadia', 'Usman', 'Zara'],
    'Age': [22, 25, 23, 21, 24, 26, 28, 22, 27, 23],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Multan', 'Faisalabad', 'Peshawar', 'Quetta', 'Rawalpindi', 'Hyderabad', 'Gujranwala'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Salary': [45000, 52000, 48000, 43000, 50000, 55000, 60000, 47000, 58000, 49000]
}

In [21]:
df = pd.DataFrame(data)  #DataFrame ek 2D (2-dimensional) table hota hai — rows aur columns ke form me,jaise Excel sheet ya database table.
#DataFrame ka use hota hai data ko store, analyze, aur process karne ke liye.
df

Name  Age        City  Gender  Salary
0     Ali   22      Lahore    Male   45000
1    Sara   25     Karachi  Female   52000
2    Omar   23   Islamabad    Male   48000
3  Ayesha   21      Multan  Female   43000
4   Bilal   24  Faisalabad    Male   50000
5  Fatima   26    Peshawar  Female   55000
6  Hassan   28      Quetta    Male   60000
7   Nadia   22  Rawalpindi  Female   47000
8   Usman   27   Hyderabad    Male   58000
9    Zara   23  Gujranwala  Female   49000

In [25]:
df.shape[0] #rows
df.shape[1] #coloumn

5

In [27]:
# Rename columns   --  we  also rename rows using index
df.rename(columns={
    'Name': 'Full_Name',
    'Age': 'Years',
    'City': 'Location',
    'Gender': 'Sex',
    'Salary': 'Income'
}, inplace=True)    ## inplace=False (default--original no change)( inplace = True# Original DataFrame me B column rename ho gaya)



In [28]:
df


Full_Name  Years    Location     Sex  Income
0       Ali     22      Lahore    Male   45000
1      Sara     25     Karachi  Female   52000
2      Omar     23   Islamabad    Male   48000
3    Ayesha     21      Multan  Female   43000
4     Bilal     24  Faisalabad    Male   50000
5    Fatima     26    Peshawar  Female   55000
6    Hassan     28      Quetta    Male   60000
7     Nadia     22  Rawalpindi  Female   47000
8     Usman     27   Hyderabad    Male   58000
9      Zara     23  Gujranwala  Female   49000

In [7]:
df.to_csv("sister.csv")  #Pandas ka ek method hai jo DataFrame ko CSV file me save karta hai.----- csv means: data in rows and coloumns--

In [29]:
df.to_csv("sisters_index_false.csv", index=False) #Row indexes: save nahi honge (kyunki index=False diya hai).
#header=False  -->  Column names include nahi karega

In [30]:
df.head(4)  # shows only 4 1st rows


Full_Name  Years   Location     Sex  Income
0       Ali     22     Lahore    Male   45000
1      Sara     25    Karachi  Female   52000
2      Omar     23  Islamabad    Male   48000
3    Ayesha     21     Multan  Female   43000

In [10]:
df.tail(4) #show only 4 last rows

Full_Name  Years    Location     Sex  Income
6    Hassan     28      Quetta    Male   60000
7     Nadia     22  Rawalpindi  Female   47000
8     Usman     27   Hyderabad    Male   58000
9      Zara     23  Gujranwala  Female   49000

In [31]:
df.describe() #DataFrame ke numerical columns (jaise Age, Salary, etc.) ke liye important statistics calculate karta hai

Years        Income
count  10.000000     10.000000
mean   24.100000  50700.000000
std     2.330951   5538.752367
min    21.000000  43000.000000
25%    22.250000  47250.000000
50%    23.500000  49500.000000
75%    25.750000  54250.000000
max    28.000000  60000.000000

In [32]:
data1 = pd.read_csv("sisters_index_false.csv")  #read_csv() → pandas ka function jo CSV file ko read karta hai

In [33]:
data1

Full_Name  Years    Location     Sex  Income
0       Ali     22      Lahore    Male   45000
1      Sara     25     Karachi  Female   52000
2      Omar     23   Islamabad    Male   48000
3    Ayesha     21      Multan  Female   43000
4     Bilal     24  Faisalabad    Male   50000
5    Fatima     26    Peshawar  Female   55000
6    Hassan     28      Quetta    Male   60000
7     Nadia     22  Rawalpindi  Female   47000
8     Usman     27   Hyderabad    Male   58000
9      Zara     23  Gujranwala  Female   49000

In [37]:
print(data1.columns)

data1["Full_Name"]   #shows full name coloumn


Index(['Full_Name', 'Years', 'Location', 'Sex', 'Income'], dtype='object')


0       Ali
1      Sara
2      Omar
3    Ayesha
4     Bilal
5    Fatima
6    Hassan
7     Nadia
8     Usman
9      Zara
Name: Full_Name, dtype: object

In [46]:
data1.columns = data1.columns.str.lower()  #convert columns into lowercase
print(data1)

  full_name  years    location     sex  income
0       Ali     22      Lahore    Male   45000
1      Sara     25     Karachi  Female   52000
2      Omar     23   Islamabad    Male   48000
3    Ayesha   2004      Multan  Female    2004
4     Bilal     24  Faisalabad    Male   50000
5    Fatima     26    Peshawar  Female   55000
6    Hassan     28      Quetta    Male   60000
7     Nadia     22  Rawalpindi  Female   47000
8     Usman     27   Hyderabad    Male   58000
9      Zara     23  Gujranwala  Female   49000


In [41]:
data1["Income"][3]=2004      #update ho jyn gi but 


C:\Users\Neha\AppData\Local\Temp\ipykernel_13556\680237713.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data1["Income"][3]=2004
C:\Users\Neha\AppData\Local\Temp\ipykernel_13556\680237713.py:1: SettingWithCopyWarning: 
A value is tryin

In [42]:
data1

Full_Name  Years    Location     Sex  Income
0       Ali     22      Lahore    Male   45000
1      Sara     25     Karachi  Female   52000
2      Omar     23   Islamabad    Male   48000
3    Ayesha   2004      Multan  Female    2004
4     Bilal     24  Faisalabad    Male   50000
5    Fatima     26    Peshawar  Female   55000
6    Hassan     28      Quetta    Male   60000
7     Nadia     22  Rawalpindi  Female   47000
8     Usman     27   Hyderabad    Male   58000
9      Zara     23  Gujranwala  Female   49000

In [ ]:
data1.to_csv("neha.csv")  #Pandas ka ek method hai jo DataFrame ko CSV file me save karta hai.

In [47]:
print(len(data1))


10


In [48]:
# 👇 Yahan hum 9 index labels de rahe hain
data1.index = ["first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth","tenth"]

print(data1)

        full_name  years    location     sex  income
first         Ali     22      Lahore    Male   45000
second       Sara     25     Karachi  Female   52000
third        Omar     23   Islamabad    Male   48000
fourth     Ayesha   2004      Multan  Female    2004
fifth       Bilal     24  Faisalabad    Male   50000
sixth      Fatima     26    Peshawar  Female   55000
seventh    Hassan     28      Quetta    Male   60000
eighth      Nadia     22  Rawalpindi  Female   47000
ninth       Usman     27   Hyderabad    Male   58000
tenth        Zara     23  Gujranwala  Female   49000


#InDepth Advance Concept


In [ ]:
# pandas --> opensource data analysis libaray in python --> if we perform in Ecxcel we dont analysis in ML 
#Pandas is an open-source Python library used for data storage, cleaning, and analysis.Unlike Excel, Pandas allows us to perform advanced data analysis and machine learning tasks easily and efficiently.

#handle lage data set efficently but Excel slower
#Any type of data (CSV, JSON, SQL, web API) easily load kar sakte ho but excel mostly have data in tabular form
#Missing values, duplicates, transformations easily handle hoti hain but in ExcelManual or limited functions; cumbersome for big data

In [ ]:
# python list , tuple , dic donot provide a such functionality to perform data analysis then we depend on external library pandas

#but uses a power or speed of numpy(written in c) 



#pandas have 2 types of Data Structure
# 1- series     --> its a one dimensional arrays with indexes, its store a single row of data in dataframe .(any type of data)
#Example    data = pd.Series([10, 20.5, 'Ali', True, None], index=['a', 'b', 'c', 'd', 'e'])   ---    print(data)   --dtype(objects)

# 2- Dataframes    --> A DataFrame is a tabular data structure that consists of multiple rows and columns, similar to a spreadsheet.(different type of data)





In [49]:
ser = pd.Series(np.random.rand(34))
#Ek pandas Series banai gayi hai jisme 34 random floating-point numbers (0 se 1 ke beech) hain.Aur usko variable ser me store kar liya gaya hai.

In [51]:
ser

0     0.520446
1     0.007670
2     0.192202
3     0.467364
4     0.947691
5     0.923046
6     0.313248
7     0.624093
8     0.178615
9     0.039893
10    0.930146
11    0.639215
12    0.474726
13    0.639500
14    0.039572
15    0.391199
16    0.162523
17    0.772180
18    0.056110
19    0.747497
20    0.991734
21    0.359360
22    0.578042
23    0.963076
24    0.106216
25    0.522620
26    0.935119
27    0.420723
28    0.583789
29    0.573001
30    0.484272
31    0.902956
32    0.286001
33    0.089469
dtype: float64

In [52]:
newdf = pd.DataFrame(np.random.rand(334, 10), index=np.arange(334))

In [54]:
newdf


0         1         2         3         4         5         6  \
0    0.995270  0.779945  0.162700  0.991329  0.378515  0.913293  0.967438   
1    0.379742  0.430489  0.897666  0.314325  0.007045  0.775431  0.204405   
2    0.800453  0.506817  0.603376  0.021993  0.860386  0.137411  0.127668   
3    0.202693  0.957160  0.334011  0.922495  0.539059  0.337126  0.720317   
4    0.146934  0.910251  0.719336  0.559378  0.525471  0.310852  0.635233   
..        ...       ...       ...       ...       ...       ...       ...   
329  0.155896  0.268694  0.188241  0.018962  0.685070  0.858735  0.020284   
330  0.070929  0.458959  0.971450  0.308556  0.777024  0.971196  0.240956   
331  0.263225  0.846001  0.146840  0.436902  0.275580  0.669815  0.305927   
332  0.150775  0.777659  0.105780  0.444835  0.507137  0.608118  0.480826   
333  0.009649  0.394014  0.719624  0.581311  0.397038  0.921421  0.882507   

            7         8         9  
0    0.611785  0.626833  0.515096  
1    0.324513  0.984132  0.921765  
2    0.220047  0.794232  0.610821  
3    0.537497  0.693791  0.058060  
4    0.503725  0.759810  0.477605  
..        ...       ...       ...  
329  0.099269  0.090975  0.590754  
330  0.970493  0.759290  0.851252  
331  0.072635  0.097826  0.725617  
332  0.091122  0.699209  0.631124  
333  0.346694  0.941876  0.373605  

[334 rows x 10 columns]

In [ ]:
newdf.head(10)

In [55]:
newdf.dtypes   #each coloumn has a different datatypes...

0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8    float64
9    float64
dtype: object

In [56]:
newdf[0][1]="neha"   #0 = coloumn   ;  1= row
print(newdf)

            0         1         2         3         4         5         6  \
0     0.99527  0.779945  0.162700  0.991329  0.378515  0.913293  0.967438   
1        neha  0.430489  0.897666  0.314325  0.007045  0.775431  0.204405   
2    0.800453  0.506817  0.603376  0.021993  0.860386  0.137411  0.127668   
3    0.202693  0.957160  0.334011  0.922495  0.539059  0.337126  0.720317   
4    0.146934  0.910251  0.719336  0.559378  0.525471  0.310852  0.635233   
..        ...       ...       ...       ...       ...       ...       ...   
329  0.155896  0.268694  0.188241  0.018962  0.685070  0.858735  0.020284   
330  0.070929  0.458959  0.971450  0.308556  0.777024  0.971196  0.240956   
331  0.263225  0.846001  0.146840  0.436902  0.275580  0.669815  0.305927   
332  0.150775  0.777659  0.105780  0.444835  0.507137  0.608118  0.480826   
333  0.009649  0.394014  0.719624  0.581311  0.397038  0.921421  0.882507   

            7         8         9  
0    0.611785  0.626833  0.515096  
1  

C:\Users\Neha\AppData\Local\Temp\ipykernel_13556\1402154791.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][1]="neha"   #0 = coloumn   ;  1= row
C:\Users\Neha\AppData\Local\Temp\ipykernel_13556\1402154791.py:1: FutureWarning: Se

In [57]:
newdf.dtypes


0     object
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8    float64
9    float64
dtype: object

In [58]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [61]:
newdf.columns

RangeIndex(start=0, stop=10, step=1)

In [62]:
newdf.to_numpy   #convert  it into numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4         5         6  \
0     0.99527  0.779945  0.162700  0.991329  0.378515  0.913293  0.967438   
1        neha  0.430489  0.897666  0.314325  0.007045  0.775431  0.204405   
2    0.800453  0.506817  0.603376  0.021993  0.860386  0.137411  0.127668   
3    0.202693  0.957160  0.334011  0.922495  0.539059  0.337126  0.720317   
4    0.146934  0.910251  0.719336  0.559378  0.525471  0.310852  0.635233   
..        ...       ...       ...       ...       ...       ...       ...   
329  0.155896  0.268694  0.188241  0.018962  0.685070  0.858735  0.020284   
330  0.070929  0.458959  0.971450  0.308556  0.777024  0.971196  0.240956   
331  0.263225  0.846001  0.146840  0.436902  0.275580  0.669815  0.305927   
332  0.150775  0.777659  0.105780  0.444835  0.507137  0.608118  0.480826   
333  0.009649  0.394014  0.719624  0.581311  0.397038  0.921421  0.882507   

            7         8         9  
0  

In [63]:
newdf.T   #transformations(where rowa become column)

0         1         2         3         4         5         6    \
0   0.99527      neha  0.800453  0.202693  0.146934  0.717123  0.327174   
1  0.779945  0.430489  0.506817   0.95716  0.910251  0.650871   0.97107   
2    0.1627  0.897666  0.603376  0.334011  0.719336  0.848089  0.466508   
3  0.991329  0.314325  0.021993  0.922495  0.559378  0.313882  0.939347   
4  0.378515  0.007045  0.860386  0.539059  0.525471  0.398879  0.298649   
5  0.913293  0.775431  0.137411  0.337126  0.310852  0.758615  0.950728   
6  0.967438  0.204405  0.127668  0.720317  0.635233  0.957402  0.186728   
7  0.611785  0.324513  0.220047  0.537497  0.503725  0.903009  0.798857   
8  0.626833  0.984132  0.794232  0.693791   0.75981  0.602696  0.168546   
9  0.515096  0.921765  0.610821   0.05806  0.477605  0.918355  0.711736   

        7         8         9    ...       324       325       326       327  \
0  0.389074  0.434762  0.048676  ...  0.297865   0.27094  0.039385  0.150974   
1  0.092903  0.454054  0.352375  ...    0.1678  0.275671  0.178886  0.415674   
2  0.500063  0.425774   0.28979  ...  0.887798  0.058158  0.936519  0.734924   
3  0.921397  0.582344   0.51311  ...  0.219129  0.153262  0.941102  0.268095   
4  0.487979  0.033468   0.46009  ...  0.241751  0.959498  0.442503  0.687308   
5  0.858783  0.121965  0.274537  ...  0.114967  0.297861  0.802142  0.767454   
6  0.075144  0.607475  0.539542  ...  0.700915  0.206005  0.654337  0.088396   
7  0.741027  0.645158  0.967223  ...  0.770358  0.325478   0.41672  0.357857   
8  0.518804  0.375562   0.78988  ...  0.346929  0.393821  0.487701  0.714477   
9  0.464828  0.113673  0.355144  ...  0.289538  0.857799  0.287719  0.992667   

        328       329       330       331       332       333  
0  0.602357  0.155896  0.070929  0.263225  0.150775  0.009649  
1   0.32168  0.268694  0.458959  0.846001  0.777659  0.394014  
2  0.130185  0.188241   0.97145   0.14684   0.10578  0.719624  
3  0.824283  0.018962  0.308556  0.436902  0.444835  0.581311  
4  0.991613   0.68507  0.777024   0.27558  0.507137  0.397038  
5  0.526378  0.858735  0.971196  0.669815  0.608118  0.921421  
6  0.670984  0.020284  0.240956  0.305927  0.480826  0.882507  
7  0.074898  0.099269  0.970493  0.072635  0.091122  0.346694  
8  0.428502  0.090975   0.75929  0.097826  0.699209  0.941876  
9  0.679371  0.590754  0.851252  0.725617  0.631124  0.373605  

[10 rows x 334 columns]

In [64]:
newdf.T.T  #transformations(where column become rows)

0         1         2         3         4         5         6  \
0     0.99527  0.779945    0.1627  0.991329  0.378515  0.913293  0.967438   
1        neha  0.430489  0.897666  0.314325  0.007045  0.775431  0.204405   
2    0.800453  0.506817  0.603376  0.021993  0.860386  0.137411  0.127668   
3    0.202693   0.95716  0.334011  0.922495  0.539059  0.337126  0.720317   
4    0.146934  0.910251  0.719336  0.559378  0.525471  0.310852  0.635233   
..        ...       ...       ...       ...       ...       ...       ...   
329  0.155896  0.268694  0.188241  0.018962   0.68507  0.858735  0.020284   
330  0.070929  0.458959   0.97145  0.308556  0.777024  0.971196  0.240956   
331  0.263225  0.846001   0.14684  0.436902   0.27558  0.669815  0.305927   
332  0.150775  0.777659   0.10578  0.444835  0.507137  0.608118  0.480826   
333  0.009649  0.394014  0.719624  0.581311  0.397038  0.921421  0.882507   

            7         8         9  
0    0.611785  0.626833  0.515096  
1    0.324513  0.984132  0.921765  
2    0.220047  0.794232  0.610821  
3    0.537497  0.693791   0.05806  
4    0.503725   0.75981  0.477605  
..        ...       ...       ...  
329  0.099269  0.090975  0.590754  
330  0.970493   0.75929  0.851252  
331  0.072635  0.097826  0.725617  
332  0.091122  0.699209  0.631124  
333  0.346694  0.941876  0.373605  

[334 rows x 10 columns]

In [67]:
newdf.sample(10) #just return a random samples---

0         1         2         3         4         5         6  \
327  0.150974  0.415674  0.734924  0.268095  0.687308  0.767454  0.088396   
144  0.940176  0.372556  0.988332  0.309535  0.424850  0.446816  0.483070   
261  0.245806  0.668226  0.281422  0.903497  0.151719  0.299851  0.568909   
297  0.191546  0.102380  0.144496  0.398806  0.783119  0.593175  0.452950   
69   0.550932  0.801129  0.789609  0.714070  0.433416  0.964064  0.360212   
31   0.729731  0.647765  0.176312  0.362810  0.370346  0.369466  0.152979   
132  0.134539  0.988110  0.848990  0.334137  0.085756  0.806624  0.532472   
179  0.609271  0.410853  0.259405  0.119091  0.290687  0.264791  0.045752   
221  0.747852  0.203544  0.205480  0.546395  0.386356  0.511817  0.256482   
326  0.039385  0.178886  0.936519  0.941102  0.442503  0.802142  0.654337   

            7         8         9  
327  0.357857  0.714477  0.992667  
144  0.986672  0.956924  0.090879  
261  0.803896  0.570527  0.783471  
297  0.747372  0.194318  0.469790  
69   0.278254  0.086425  0.769666  
31   0.559772  0.168414  0.652498  
132  0.145688  0.362490  0.568210  
179  0.651190  0.648738  0.553123  
221  0.018340  0.113287  0.643211  
326  0.416720  0.487701  0.287719

In [68]:
newdf[0]

0       0.99527
1          neha
2      0.800453
3      0.202693
4      0.146934
         ...   
329    0.155896
330    0.070929
331    0.263225
332    0.150775
333    0.009649
Name: 0, Length: 334, dtype: object

In [72]:
newdf1=np.arange(99) #np.arange() NumPy ka function hai jo numbers ki sequence (range) banata hai,

In [71]:
newdf1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [75]:
newdf1.reshape(3,33) 

# 3- rows → kitni rows chahiye   -   33- columns → har row me kitne elements hone chahiye
#reshape() ka use array ki shape (dimension) badalne ke liye hota hai —data same rehta hai, sirf usko naye rows aur columns ke structure me arrange kar dete hain.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [76]:
newdf2= newdf1.ravel()  #👉 multi-dimensional array ko ek single flat (1D) array me convert karna.

In [78]:
newdf2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [79]:
newdf2.shape   

(99,)

In [80]:
import numpy as np

newdf2 = np.arange(12).reshape(3, 4)
print(newdf2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# NumPY Axis:

# -----------------------------
# 1️⃣  Example for 1D Array
# -----------------------------
# A 1D array has only ONE direction(Access) (Axis 0)----------------------arr1 = np.array([10, 20, 30, 40])





# -----------------------------
# 2️⃣  Example for 2D Array
# -----------------------------
# A 2D array has TWO directions:
# → Axis 0 : moves vertically (down the rows)
# → Axis 1 : moves horizontally (across the columns) ---------------------
 # arr2 = np.array([
   #  [1, 2, 3],   # Row 0
   # [4, 5, 6]    # Row 1
#])



In [82]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [83]:
ar = np.array(x)

In [85]:
ar.sum(axis=0)  #coloumn vise value add 

array([12,  8,  9])

In [86]:
ar.sum(axis=1) #rows vise values add...


array([ 6, 15,  8])

In [87]:
ar.flat

In [88]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [89]:
ar.ndim

2

In [90]:
ar.size  #no. of elements in array 

9

In [91]:
ar.nbytes         #nbytes ek attribute hota hai (method nahi), jo batata hai array ke total bytes (memory size).

72

In [92]:
one = np.array([1 , 45 , 678 , 89 , 90])


In [93]:
one.argmax()   #return a maximum valure as a index /////
one.argmin()  #retuen a minmium values as a index


np.int64(0)

In [95]:
one.argsort()  #return array as a assending value is...

array([0, 1, 3, 4, 2])

In [96]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [97]:
ar.argmin()   #retum smallest value as a index

np.int64(8)

In [100]:
ar.argmax(axis=0)   #return a max value as as a index value--column vise

array([2, 1, 1])

In [99]:
ar.argmax(axis=1)   #return a maximum value as a row vise

array([2, 2, 0])

In [102]:
newdf

0         1         2         3         4         5         6  \
0     0.99527  0.779945  0.162700  0.991329  0.378515  0.913293  0.967438   
1        neha  0.430489  0.897666  0.314325  0.007045  0.775431  0.204405   
2    0.800453  0.506817  0.603376  0.021993  0.860386  0.137411  0.127668   
3    0.202693  0.957160  0.334011  0.922495  0.539059  0.337126  0.720317   
4    0.146934  0.910251  0.719336  0.559378  0.525471  0.310852  0.635233   
..        ...       ...       ...       ...       ...       ...       ...   
329  0.155896  0.268694  0.188241  0.018962  0.685070  0.858735  0.020284   
330  0.070929  0.458959  0.971450  0.308556  0.777024  0.971196  0.240956   
331  0.263225  0.846001  0.146840  0.436902  0.275580  0.669815  0.305927   
332  0.150775  0.777659  0.105780  0.444835  0.507137  0.608118  0.480826   
333  0.009649  0.394014  0.719624  0.581311  0.397038  0.921421  0.882507   

            7         8         9  
0    0.611785  0.626833  0.515096  
1    0.324513  0.984132  0.921765  
2    0.220047  0.794232  0.610821  
3    0.537497  0.693791  0.058060  
4    0.503725  0.759810  0.477605  
..        ...       ...       ...  
329  0.099269  0.090975  0.590754  
330  0.970493  0.759290  0.851252  
331  0.072635  0.097826  0.725617  
332  0.091122  0.699209  0.631124  
333  0.346694  0.941876  0.373605  

[334 rows x 10 columns]

In [108]:
newdf.drop(3)  #delete a row 

0         1         2         3         4         5         6  \
0     0.99527  0.779945  0.162700  0.991329  0.378515  0.913293  0.967438   
1        neha  0.430489  0.897666  0.314325  0.007045  0.775431  0.204405   
2    0.800453  0.506817  0.603376  0.021993  0.860386  0.137411  0.127668   
4    0.146934  0.910251  0.719336  0.559378  0.525471  0.310852  0.635233   
5    0.717123  0.650871  0.848089  0.313882  0.398879  0.758615  0.957402   
..        ...       ...       ...       ...       ...       ...       ...   
329  0.155896  0.268694  0.188241  0.018962  0.685070  0.858735  0.020284   
330  0.070929  0.458959  0.971450  0.308556  0.777024  0.971196  0.240956   
331  0.263225  0.846001  0.146840  0.436902  0.275580  0.669815  0.305927   
332  0.150775  0.777659  0.105780  0.444835  0.507137  0.608118  0.480826   
333  0.009649  0.394014  0.719624  0.581311  0.397038  0.921421  0.882507   

            7         8         9  
0    0.611785  0.626833  0.515096  
1    0.324513  0.984132  0.921765  
2    0.220047  0.794232  0.610821  
4    0.503725  0.759810  0.477605  
5    0.903009  0.602696  0.918355  
..        ...       ...       ...  
329  0.099269  0.090975  0.590754  
330  0.970493  0.759290  0.851252  
331  0.072635  0.097826  0.725617  
332  0.091122  0.699209  0.631124  
333  0.346694  0.941876  0.373605  

[333 rows x 10 columns]

In [123]:
newdf.drop([1 , 4 , 6 ,9], axis=1 , inplace=True)   #delete a column as column vise  but original data same just return a copy agr orginal b 
#change krna chahtyn hn toh aik new varaible bna kr newdrop1 =  bna kr phir print krwana pir change ho ga 

#usi dataframe me change ho ga....


#Jab aap inplace=True likhte ho, to original DataFrame me hi change ho jata hai, naya copy return nahi hota.


#inplace=False (default)Naya DataFrame return karega, original safe rahega

In [124]:
newdf

0         2         3         5         7         8
0     0.99527  0.162700  0.991329  0.913293  0.611785  0.626833
1        neha  0.897666  0.314325  0.775431  0.324513  0.984132
2    0.800453  0.603376  0.021993  0.137411  0.220047  0.794232
3    0.202693  0.334011  0.922495  0.337126  0.537497  0.693791
4    0.146934  0.719336  0.559378  0.310852  0.503725  0.759810
..        ...       ...       ...       ...       ...       ...
329  0.155896  0.188241  0.018962  0.858735  0.099269  0.090975
330  0.070929  0.971450  0.308556  0.971196  0.970493  0.759290
331  0.263225  0.146840  0.436902  0.669815  0.072635  0.097826
332  0.150775  0.105780  0.444835  0.608118  0.091122  0.699209
333  0.009649  0.719624  0.581311  0.921421  0.346694  0.941876

[334 rows x 6 columns]

In [ ]:
#remove null value in ---The dropna() method removes the rows that contains NULL values.




In [128]:
newdf[3].isnull()    #-----.isnull() ------Ye function missing values (NaN) check karta hai(Null value hn=True return kry ga)
#(False return kryn ga agr missing values na hui)

0      False
1      False
2      False
3      False
4      False
       ...  
329    False
330    False
331    False
332    False
333    False
Name: 3, Length: 334, dtype: bool

In [129]:
newdf[2]=None  #each column contain null value

In [131]:
newdf

0     2         3         5         7         8
0     0.99527  None  0.991329  0.913293  0.611785  0.626833
1        neha  None  0.314325  0.775431  0.324513  0.984132
2    0.800453  None  0.021993  0.137411  0.220047  0.794232
3    0.202693  None  0.922495  0.337126  0.537497  0.693791
4    0.146934  None  0.559378  0.310852  0.503725  0.759810
..        ...   ...       ...       ...       ...       ...
329  0.155896  None  0.018962  0.858735  0.099269  0.090975
330  0.070929  None  0.308556  0.971196  0.970493  0.759290
331  0.263225  None  0.436902  0.669815  0.072635  0.097826
332  0.150775  None  0.444835  0.608118  0.091122  0.699209
333  0.009649  None  0.581311  0.921421  0.346694  0.941876

[334 rows x 6 columns]

In [132]:
newdf[2].isnull()

0      True
1      True
2      True
3      True
4      True
       ... 
329    True
330    True
331    True
332    True
333    True
Name: 2, Length: 334, dtype: bool

In [136]:
newdf.loc[:, [2]] = 56     #loc--location ---------Part	Meaning
# :	All rows select kar raha hai
# [2]	Column jiska label 2 hai
# = 56	Har cell me value 56 assign kar raha hai

In [134]:
newdf

0   2         3         5         7         8
0     0.99527  56  0.991329  0.913293  0.611785  0.626833
1        neha  56  0.314325  0.775431  0.324513  0.984132
2    0.800453  56  0.021993  0.137411  0.220047  0.794232
3    0.202693  56  0.922495  0.337126  0.537497  0.693791
4    0.146934  56  0.559378  0.310852  0.503725  0.759810
..        ...  ..       ...       ...       ...       ...
329  0.155896  56  0.018962  0.858735  0.099269  0.090975
330  0.070929  56  0.308556  0.971196  0.970493  0.759290
331  0.263225  56  0.436902  0.669815  0.072635  0.097826
332  0.150775  56  0.444835  0.608118  0.091122  0.699209
333  0.009649  56  0.581311  0.921421  0.346694  0.941876

[334 rows x 6 columns]

In [137]:
#.loc[]  (Label-based selection) aur .iloc[] (Integer position-based selection

# 👉 Matlab: row/column number positions ke basis par select karta hai (0,1,2,...))---- mostly used to select or update a data in dataframes

# df.loc['a']            # Row with index label 'a'
# df.loc['b', 'City']    # Single value: Karachi
# df.loc[:, 'Name']      # All rows, only 'Name' column
# df.loc['a':'c', ['Name', 'Age']]  # Multiple rows & columns by labels







#iloc
# df.iloc[0]           # Row at position 0
# df.iloc[1, 2]        # Row 1, Column 2 → Karachi
# df.iloc[:, 0]        # All rows, first column (Name)
# df.iloc[0:2, 1:3]    # Rows 0–1, Columns 1–2

